name = "detoxr"
bin = "bin/detoxr"
vcs = "git"
with_pop = false
with_sqlite = false
with_dep = false
with_webpack = false
with_nodejs = false
with_yarn = true
with_docker = true
with_grifts = true
as_web = true
as_api = false
